Added Exchange of Authoriation Code for Access Token (untested)
theraphosida/apollon pull request #8
Opened 2022-03-31 10:41 UTC by MichaelSchule

#APN-41
#APN-44

2022-03-31 10:48 UTC, MichaelSchule commented on ApollonBackend/ApollonBackend/Authentication/AuthorizationCodeAuthenticator.cs
> +        private const string c_clientSecret = "607b0bdd7f6544cb933e2103da58bee4";
ups

2022-04-20 08:55 UTC, lennart167 requested changes

2022-04-20 08:55 UTC, lennart167 commented on ApollonBackend/ApollonBackend/Authentication/AuthorizationCodeAuthenticator.cs
> +            AccessToken authorizationToken = new AccessToken();
Please rename variable to accessToken

2022-04-20 08:55 UTC, lennart167 commented on ApollonBackend/ApollonBackend/Authentication/ClientCredentialsAuthenticator.cs
> +            AccessToken authorizationToken = new AccessToken();
Please rename variable to accessToken

2022-04-27 08:42 UTC, closed without merging